[package]
name = "yaw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
glam = "0.29.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
sdl2 = { version = "0.37.0", features = ["ttf", "image"], path = "rust-sdl2" }
